name: JonVanhala
favicon: null
layout_spectrum: 0.0033253394067287445
typography_spectrum: 0.9431912691798061
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5623932725284249
  lightness: 0.4675334522034973
  saturation: 0.9302836095448583
  rhythmicContrast: 0.3189138458110392
purpose: []
